version: '3'
services:
  # apache2:
  #   container_name: apache2
  #   build:
  #     context: ./apache2
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   networks:
  #     - app-network
  #   restart: always
  db:
    container_name: db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    expose:
      - "3306"
    networks:
      - app-network
  frontend:
    container_name: frontend
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5173:5173"
    networks:
      - app-network
  backend:
    container_name: backend
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    environment:
      - PORT=$PORT
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PORT=$DB_PORT
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=$DB_DATABASE
    depends_on:
      - db
      # - apache2
    expose:
      - "3000"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge