version: '3'
services:
  # apache2:
  #   container_name: apache2
  #   build:
  #     context: ./apache2
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   networks:
  #     - app-network
  #   restart: always
  db:
    container_name: db
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - "$DB_PORT:3306"
    expose:
      - "$DB_PORT"
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
        - DB_HOST=$DB_HOST
        - DB_USER=$DB_USER
        - DB_PORT=$DB_PORT
        - DB_PASSWORD=$DB_PASSWORD
        - DB_DATABASE=$DB_DATABASE
    ports:
      - "127.0.0.1:3000:3000"
    # depends_on:
    #   - apache2
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge